################################################################################
#                        INITIALIZATION MODULE
################################################################################
#^* GOAL: inizialize the lists for the maps of different variables/parameters:
#^******************************************************************************
#^* PROGRAMMER: Matteo Darienzo, University of Padua, Italy
#^******************************************************************************
#^* CREATED/MODIFIED: 2025/11/28
#^******************************************************************************
#^*
#^******************************************************************************
#^* REF.:
#^******************************************************************************
#^* to do: 
#^******************************************************************************
#^* COMMENTS: initialization of all variables and parameters to be computed.
#^*           For now, not a very fancy code. Think about something better later
################################################################################
pix=0
# AMAX:
AMS<-vector(mode="list",length=nrow(tmp_array)*ncol(tmp_array))
# res_MK<-vector(mode="list",length=nrow(tmp_array)*ncol(tmp_array))
sensslope_AMAX_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
sensslope_AMAX_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
sensslope_AMAX_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
sensslope_AMAX_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
signif_trend_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
signif_trend_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
signif_trend_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
signif_trend_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
z_MK_AMAX_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
z_MK_AMAX_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
z_MK_AMAX_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
z_MK_AMAX_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
pval_MK_AMAX_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
pval_MK_AMAX_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
pval_MK_AMAX_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
pval_MK_AMAX_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))

# n
n_senss<-rep(NA,nrow(tmp_array)*ncol(tmp_array)) 
# vector(mode="list",length=nrow(tmp_array)*ncol(tmp_array))
# n_MK<-vector(mode="list",length=nrow(tmp_array)*ncol(tmp_array))
pval_MK_n<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
z_MK_n<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
n_ordev<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
lmfit_n_inter<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
lmfit_n_slope<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
signif_trend_n<-rep(NA,nrow(tmp_array)*ncol(tmp_array))

# ns:
a_w_MAP_ns_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_MAP_ns_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_MAP_ns_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_MAP_ns_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
b_w_MAP_ns_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
b_w_MAP_ns_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
b_w_MAP_ns_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
b_w_MAP_ns_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_MAP_ns_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_MAP_ns_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_MAP_ns_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_MAP_ns_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
b_C_MAP_ns_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
b_C_MAP_ns_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
b_C_MAP_ns_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
b_C_MAP_ns_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))

a_w_fmins_ns_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_fmins_ns_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_fmins_ns_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_fmins_ns_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
b_w_fmins_ns_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
b_w_fmins_ns_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
b_w_fmins_ns_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
b_w_fmins_ns_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_fmins_ns_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_fmins_ns_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_fmins_ns_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_fmins_ns_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
b_C_fmins_ns_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
b_C_fmins_ns_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
b_C_fmins_ns_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
b_C_fmins_ns_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))

a_w_quant5_Post_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_quant50_Post_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_quant95_Post_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_quant5_Post_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_quant50_Post_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_quant95_Post_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_quant5_Post_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_quant50_Post_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_quant95_Post_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_quant5_Post_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_quant50_Post_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_quant95_Post_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))

b_w_quant5_Post_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
b_w_quant50_Post_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
b_w_quant95_Post_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
b_w_quant5_Post_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
b_w_quant50_Post_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
b_w_quant95_Post_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
b_w_quant5_Post_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
b_w_quant50_Post_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
b_w_quant95_Post_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
b_w_quant5_Post_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
b_w_quant50_Post_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
b_w_quant95_Post_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))

a_C_quant5_Post_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_quant50_Post_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_quant95_Post_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_quant5_Post_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_quant50_Post_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_quant95_Post_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_quant5_Post_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_quant50_Post_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_quant95_Post_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_quant5_Post_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_quant50_Post_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_quant95_Post_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))

b_C_quant5_Post_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
b_C_quant50_Post_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
b_C_quant95_Post_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
b_C_quant5_Post_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
b_C_quant50_Post_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
b_C_quant95_Post_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
b_C_quant5_Post_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
b_C_quant50_Post_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
b_C_quant95_Post_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
b_C_quant5_Post_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
b_C_quant50_Post_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
b_C_quant95_Post_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))

# stat:
a_w_stat_quant5_Post_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_stat_quant50_Post_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_stat_quant95_Post_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_stat_quant5_Post_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_stat_quant50_Post_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_stat_quant95_Post_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_stat_quant5_Post_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_stat_quant50_Post_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_stat_quant95_Post_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_stat_quant5_Post_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_stat_quant50_Post_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_stat_quant95_Post_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_stat_quant5_Post_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_stat_quant50_Post_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_stat_quant95_Post_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_stat_quant5_Post_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_stat_quant50_Post_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_stat_quant95_Post_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_stat_quant5_Post_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_stat_quant50_Post_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_stat_quant95_Post_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_stat_quant5_Post_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_stat_quant50_Post_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_stat_quant95_Post_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_MAP_stat_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_MAP_stat_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_MAP_stat_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_MAP_stat_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_MAP_stat_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_MAP_stat_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_MAP_stat_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_MAP_stat_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_fmins_stat_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_fmins_stat_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_fmins_stat_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_fmins_stat_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_fmins_stat_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_fmins_stat_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_fmins_stat_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_fmins_stat_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))

# GEV stat:
a_L_gev_quant5_Post_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_L_gev_quant50_Post_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_L_gev_quant95_Post_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_L_gev_quant5_Post_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_L_gev_quant50_Post_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_L_gev_quant95_Post_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_L_gev_quant5_Post_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_L_gev_quant50_Post_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_L_gev_quant95_Post_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_L_gev_quant5_Post_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_L_gev_quant50_Post_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_L_gev_quant95_Post_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_gev_quant5_Post_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_gev_quant50_Post_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_gev_quant95_Post_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_gev_quant5_Post_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_gev_quant50_Post_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_gev_quant95_Post_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_gev_quant5_Post_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_gev_quant50_Post_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_gev_quant95_Post_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_gev_quant5_Post_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_gev_quant50_Post_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_gev_quant95_Post_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_gev_quant5_Post_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_gev_quant50_Post_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_gev_quant95_Post_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_gev_quant5_Post_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_gev_quant50_Post_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_gev_quant95_Post_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_gev_quant5_Post_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_gev_quant50_Post_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_gev_quant95_Post_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_gev_quant5_Post_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_gev_quant50_Post_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_gev_quant95_Post_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_L_MAP_gev_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_L_MAP_gev_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_L_MAP_gev_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_L_MAP_gev_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_MAP_gev_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_MAP_gev_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_MAP_gev_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_C_MAP_gev_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_MAP_gev_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_MAP_gev_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_MAP_gev_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
a_w_MAP_gev_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))

# Quantiles (2,5,10,20,50,100 years of return period):
qCurve_2yr_maxpost_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
qCurve_2yr_maxpost_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
qCurve_2yr_maxpost_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
qCurve_2yr_maxpost_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
qCurve_5yr_maxpost_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
qCurve_5yr_maxpost_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
qCurve_5yr_maxpost_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
qCurve_5yr_maxpost_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
qCurve_10yr_maxpost_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
qCurve_10yr_maxpost_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
qCurve_10yr_maxpost_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
qCurve_10yr_maxpost_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
qCurve_20yr_maxpost_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
qCurve_20yr_maxpost_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
qCurve_20yr_maxpost_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
qCurve_20yr_maxpost_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
qCurve_50yr_maxpost_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
qCurve_50yr_maxpost_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
qCurve_50yr_maxpost_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
qCurve_50yr_maxpost_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
qCurve_100yr_maxpost_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
qCurve_100yr_maxpost_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
qCurve_100yr_maxpost_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
qCurve_100yr_maxpost_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
qCurve_2yr_median_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
qCurve_2yr_median_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
qCurve_2yr_median_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
qCurve_2yr_median_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))

DIC3_ns_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
DIC3_ns_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
DIC3_ns_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
DIC3_ns_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
DIC3_stat_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
DIC3_stat_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
DIC3_stat_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
DIC3_stat_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
BIC_ns_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
BIC_ns_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
BIC_ns_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
BIC_ns_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
BIC_stat_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
BIC_stat_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
BIC_stat_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
BIC_stat_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))

loglik_bayes_stat_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
loglik_bayes_stat_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
loglik_bayes_stat_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
loglik_bayes_stat_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))

loglik_bayes_ns_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
loglik_bayes_ns_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
loglik_bayes_ns_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
loglik_bayes_ns_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))

loglik_fmins_stat_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
loglik_fmins_stat_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
loglik_fmins_stat_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
loglik_fmins_stat_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))

loglik_fmins_ns_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
loglik_fmins_ns_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
loglik_fmins_ns_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
loglik_fmins_ns_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))

unc_shape_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
unc_shape_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
unc_shape_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
unc_shape_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
unc_scale_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
unc_scale_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
unc_scale_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
unc_scale_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
unc_n_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
unc_n_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
unc_n_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
unc_n_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
unc_qnt2yrs_1h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
unc_qnt2yrs_3h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
unc_qnt2yrs_6h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))
unc_qnt2yrs_24h<-rep(NA,nrow(tmp_array)*ncol(tmp_array))


# initialization of lists for processed maps:
#############################################
# ns smev:
a_w_MAP_ns=b_w_MAP_ns=a_C_MAP_ns=b_C_MAP_ns=list()
a_w_CI_ns=b_w_CI_ns=a_C_CI_ns=b_C_CI_ns=list()
a_w_med_ns=b_w_med_ns=a_C_med_ns=b_C_med_ns=list()
a_w_fmins_ns=b_w_fmins_ns=a_C_fmins_ns=b_C_fmins_ns=list()
a_w_MaxLik_ns=b_w_MaxLik_ns=a_C_MaxLik_ns=b_C_MaxLik_ns=list()
# partns smev:
a_w_MAP_partns=b_w_MAP_partns=a_C_MAP_partns=b_C_MAP_partns=list()
a_w_CI_partns=b_w_CI_partns=a_C_CI_partns=b_C_CI_partns=list()
a_w_med_partns=b_w_med_partns=a_C_med_partns=b_C_med_partns=list()
a_w_MaxLik_partns=b_w_MaxLik_partns=a_C_MaxLik_partns=b_C_MaxLik_partns=list()
a_w_fmins_partns=b_w_fmins_partns=a_C_fmins_partns=b_C_fmins_partns=list()
# stat smev:
a_w_MAP_stat=b_w_MAP_stat=a_C_MAP_stat=b_C_MAP_stat=list()
a_w_CI_stat=b_w_CI_stat=a_C_CI_stat=b_C_CI_stat=list()
a_w_med_stat=b_w_med_stat=a_C_med_stat=b_C_med_stat=list()
a_w_MaxLik_stat=b_w_MaxLik_stat=a_C_MaxLik_stat=b_C_MaxLik_stat=list()
a_w_fmins_stat=b_w_fmins_stat=a_C_fmins_stat=b_C_fmins_stat=list()
# stat gev:
a_w_MAP_gev=a_L_MAP_gev=a_C_MAP_gev=list()
a_w_CI_gev=a_L_CI_gev=a_C_CI_gev=list()
a_w_med_gev=a_L_med_gev=a_C_med_gev=list()
# a_w_MaxLik_gev = b_w_MaxLik_gev= a_C_MaxLik_gev= b_C_MaxLik_gev=list()
# a_w_fmins_gev = a_L_fmins_gev= a_C_fmins_gev=list()

# MK Sens's trend tests:
signif_trend_AMAX=z_MK_AMAX=pval_MK_AMAX=sensslope_AMAX=list()
# % change of n and AMX per decade
n_change=AMAX_change=list()
# criteria:
signif_ns_DIC_diff3=signif_ns_DIC_diff1=signif_ns_AIC=signif_ns_BIC=list()
# likelihood ratio tests:
pval_yy_wrt_nn=pval_yy_wrt_nn_fmins=signif_fmins_ns_LRT=signif_bayes_ns_LRT=list()
# quantiles return levels:
quant_smev_ns_2yr=quant_smev_ns_5yr=quant_smev_ns_10yr=quant_smev_ns_20yr=list()
quant_smev_ns_50yr=quant_smev_ns_100yr=list()
quant_smev_ns_2yr_change=quant_smev_ns_10yr_change=quant_smev_ns_20yr_change=quant_smev_ns_50yr_change=list()
quant_smev_ns_2yr_fmins_change=quant_smev_ns_2yr_median_change=list()
